package ageutil

import (
	"fmt"
	"strings"
)

func PassphrasePromptForEncryption() (string, error) {
	pass, err := readSecret("Enter passphrase (leave empty to autogenerate a secure one):")
	if err != nil {
		return "", fmt.Errorf("could not read passphrase: %v", err)
	}
	p := string(pass)
	if p == "" {
		if p, err = GenerateAndPrintPassphrase(); err != nil {
			return "", err
		}
	} else {
		confirm, err := readSecret("Confirm passphrase:")
		if err != nil {
			return "", fmt.Errorf("could not read passphrase: %v", err)
		}
		if string(confirm) != p {
			return "", fmt.Errorf("passphrases didn't match")
		}
	}
	return p, nil
}

func GenerateAndPrintPassphrase() (string, error) {
	p := GeneratePassphrase()
	err := printfToTerminal("using autogenerated passphrase %q", p)
	if err != nil {
		return "", fmt.Errorf("could not print passphrase: %v", err)
	}
	return p, nil
}

func GeneratePassphrase() string {
	var words []string
	for i := 0; i < 10; i++ {
		words = append(words, randomWord())
	}
	return strings.Join(words, "-")
}
